### ISSUE TITLE
类型“State”不满足约束“Store<any, AnyAction>”

### ISSUE THREAD

**Issue by YangYuHub** [Jacky-Summer/nextjs-ts-antd-redux-storybook-starter#10]
![image](https://user-images.githubusercontent.com/63183404/125411474-02d23c80-e3cf-11eb-93a0-2489a71a7e95.png)

根据你的步骤安装完成redux  redux-saga  后面一直提示这个错误

**Comment by dianyuyi** [comment]
最近剛好遇到同樣問題，有類似的[參考](https://github.com/kirill-konshin/next-redux-wrapper/issues/399)
我的做法是將next-redux-wrapper從7.x降回6.0.2，不知是否對你有幫助

**Comment by Jacky-Summer** [comment]
已转为使用 `@redux/toolkit` 配置 `redux-saga`
