### ISSUE TITLE
看到了我最讨厌的Styled-components，就米有勇气看下去了

### ISSUE THREAD

**Issue by dmwin72015** [Jacky-Summer/nextjs-ts-antd-redux-storybook-starter#9]

**Comment by Jacky-Summer** [comment]
关注重点，我整个脚手架讲究配置和规范，写页面内容的没多少， styled-components 很少。想请问你们用的是什么css方案？我之后也打算把该脚手架试试换换某几种解决方案，如数据流方案，css方案试试

**Comment by dmwin72015** [comment]
之前一直用 css module，开玩笑，其实都一样，redux-saga其实可以换成dva，文件组织方便一点
